package adapter

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// Protocol families the gateway can interpret a spec for. A genuinely new
// transport still needs code; a spec composes over one of these three.
const (
	FamilyHTTPJSON     = "http-json"
	FamilyTCPFrameJSON = "tcp-frame-json"
	FamilyUDPCRCJSON   = "udp-crc-json"
)

// Spec is the declarative description of one adapter.
//
// Everything a protocol version bump usually changes -- a renamed field, a new
// operation token, a different header, a larger payload ceiling -- is data
// here. That is what lets a v1 -> v2 migration ship as a document rather than
// as a rebuild, and it is why the built-in adapters are written as specs too:
// the runtime-loading path is the only path, so it cannot rot.
type Spec struct {
	Name      string `json:"name"`
	Family    string `json:"family"`
	ServiceID string `json:"service_id"`
	Version   int    `json:"version"`
	// Endpoint overrides the registry endpoint when a variant listens
	// somewhere else. Empty means "use the service endpoint".
	Endpoint string `json:"endpoint,omitempty"`

	Wire       Wire              `json:"wire"`
	Operations map[string]OpSpec `json:"operations"`

	// SelfTest are golden vectors the adapter must satisfy before it is
	// allowed to serve traffic. See RunSelfTest.
	SelfTest []Vector `json:"self_test,omitempty"`
}

// Wire holds the transport and payload-shape parameters of a protocol version.
type Wire struct {
	// --- HTTP family ---
	ExecutePath     string            `json:"execute_path,omitempty"`
	HealthPath      string            `json:"health_path,omitempty"`
	Method          string            `json:"method,omitempty"`
	Headers         map[string]string `json:"headers,omitempty"`
	VersionHeader   string            `json:"version_header,omitempty"`
	RequestIDHeader string            `json:"request_id_header,omitempty"`

	// --- framed and datagram families ---
	MagicHex   string `json:"magic_hex,omitempty"`
	MaxPayload int    `json:"max_payload,omitempty"`
	Checksum   string `json:"checksum,omitempty"` // "crc32-ieee" or empty

	// --- request payload shape ---
	// OperationField carries the backend's operation token. Empty means the
	// operation is expressed out of band (a datagram opcode byte).
	OperationField string `json:"operation_field,omitempty"`
	// ArgumentsField nests the arguments. Empty means the payload *is* the
	// argument object.
	ArgumentsField string `json:"arguments_field,omitempty"`

	// --- response payload shape ---
	// CorrelationField is the echoed request identifier inside the payload.
	// Empty means correlation is framed-level only.
	CorrelationField string `json:"correlation_field,omitempty"`
	// ResultField holds the success payload.
	ResultField string `json:"result_field,omitempty"`
	// ErrorField nests the error object. Empty means the error fields sit at
	// the top level of the payload.
	ErrorField          string `json:"error_field,omitempty"`
	ErrorCodeField      string `json:"error_code_field,omitempty"`
	ErrorMessageField   string `json:"error_message_field,omitempty"`
	ErrorRetryableField string `json:"error_retryable_field,omitempty"`

	// --- policy ---
	// RetryableCodes are backend error codes to report as retryable even when
	// the backend does not say so.
	RetryableCodes []string `json:"retryable_codes,omitempty"`
}

// OpSpec maps one logical operation onto its backend representation.
type OpSpec struct {
	// Wire is the backend's own operation token ("uppercase", "UPPERCASE").
	Wire string `json:"wire,omitempty"`
	// OpCode is the datagram opcode for families that use one.
	OpCode int `json:"op_code,omitempty"`
	// ArgMap renames logical argument keys to backend keys. Unlisted keys pass
	// through unchanged.
	ArgMap map[string]string `json:"arg_map,omitempty"`
	// ResultKeys are the payload keys that hold the scalar answer, tried in
	// order. Service B, for instance, answers string operations in `value` and
	// numeric ones in `numericResult`, so both are listed.
	ResultKeys []string `json:"result_keys,omitempty"`
	// Passthrough emits the backend result object unchanged instead of
	// rewrapping it, which is what `metadata` needs.
	Passthrough bool `json:"passthrough,omitempty"`
}

// Vector is one golden self-test case.
//
// Vectors are recorded from the live backends, not generated by the adapter, so
// they are a genuine external check: an adapter that framed or parsed
// incorrectly could not satisfy bytes it did not produce.
type Vector struct {
	Name          string         `json:"name"`
	Operation     string         `json:"operation"`
	Arguments     map[string]any `json:"arguments,omitempty"`
	CorrelationID uint64         `json:"correlation_id,omitempty"`
	Seq           uint32         `json:"seq,omitempty"`

	// ExpectRequestHex, when set, pins the exact encoded request bytes.
	ExpectRequestHex string `json:"expect_request_hex,omitempty"`
	// ResponseHex is a recorded backend response to decode.
	ResponseHex string `json:"response_hex,omitempty"`
	// ExpectResult is the normalized result the decode must produce.
	ExpectResult map[string]any `json:"expect_result,omitempty"`
	// ExpectErrorCode asserts that decoding fails with this gateway code,
	// which is how negative vectors pin validation behaviour.
	ExpectErrorCode string `json:"expect_error_code,omitempty"`
}

// Validate checks a spec's shape before anything is built from it.
//
// This runs on every load, including specs that arrive over the admin API, so
// the constructor below can assume its inputs are structurally sane. A spec
// that fails here is rejected outright and the previously loaded adapter keeps
// serving.
func (s *Spec) Validate() error {
	if strings.TrimSpace(s.Name) == "" {
		return fmt.Errorf("adapter name must not be empty")
	}
	if strings.TrimSpace(s.ServiceID) == "" {
		return fmt.Errorf("adapter %s: service_id must not be empty", s.Name)
	}
	if s.Version <= 0 {
		return fmt.Errorf("adapter %s: version must be positive", s.Name)
	}
	if len(s.Operations) == 0 {
		return fmt.Errorf("adapter %s: at least one operation mapping is required", s.Name)
	}

	switch s.Family {
	case FamilyHTTPJSON:
		if s.Wire.ExecutePath == "" {
			return fmt.Errorf("adapter %s: http family requires wire.execute_path", s.Name)
		}
		if s.Wire.OperationField == "" || s.Wire.ArgumentsField == "" {
			return fmt.Errorf("adapter %s: http family requires operation_field and arguments_field", s.Name)
		}
	case FamilyTCPFrameJSON:
		if _, err := parseMagic(s.Wire.MagicHex); err != nil {
			return fmt.Errorf("adapter %s: %w", s.Name, err)
		}
		if s.Wire.OperationField == "" {
			return fmt.Errorf("adapter %s: framed family requires operation_field", s.Name)
		}
		if s.Wire.MaxPayload <= 0 || s.Wire.MaxPayload > 1<<24 {
			return fmt.Errorf("adapter %s: framed family requires a sane max_payload", s.Name)
		}
	case FamilyUDPCRCJSON:
		if _, err := parseMagic(s.Wire.MagicHex); err != nil {
			return fmt.Errorf("adapter %s: %w", s.Name, err)
		}
		if s.Wire.Checksum != "crc32-ieee" {
			return fmt.Errorf("adapter %s: datagram family supports checksum crc32-ieee only, got %q", s.Name, s.Wire.Checksum)
		}
		if s.Wire.MaxPayload <= 0 || s.Wire.MaxPayload > 65535 {
			return fmt.Errorf("adapter %s: datagram family requires max_payload in 1..65535", s.Name)
		}
	default:
		return fmt.Errorf("adapter %s: unknown family %q", s.Name, s.Family)
	}

	for name, op := range s.Operations {
		if strings.TrimSpace(name) == "" {
			return fmt.Errorf("adapter %s: operation key must not be empty", s.Name)
		}
		if s.Family == FamilyUDPCRCJSON {
			if op.OpCode <= 0 || op.OpCode > 255 {
				return fmt.Errorf("adapter %s: operation %q needs an op_code in 1..255", s.Name, name)
			}
		} else if op.Wire == "" {
			return fmt.Errorf("adapter %s: operation %q needs a wire token", s.Name, name)
		}
		if !op.Passthrough && len(op.ResultKeys) == 0 {
			return fmt.Errorf("adapter %s: operation %q needs result_keys or passthrough", s.Name, name)
		}
	}

	for i, v := range s.SelfTest {
		if v.Name == "" {
			return fmt.Errorf("adapter %s: self_test[%d] needs a name", s.Name, i)
		}
		if v.Operation == "" {
			return fmt.Errorf("adapter %s: self_test[%d] needs an operation", s.Name, i)
		}
		if v.ExpectRequestHex != "" {
			if _, err := hex.DecodeString(v.ExpectRequestHex); err != nil {
				return fmt.Errorf("adapter %s: self_test %q has invalid expect_request_hex: %w", s.Name, v.Name, err)
			}
		}
		if v.ResponseHex != "" {
			if _, err := hex.DecodeString(v.ResponseHex); err != nil {
				return fmt.Errorf("adapter %s: self_test %q has invalid response_hex: %w", s.Name, v.Name, err)
			}
		}
		if v.ResponseHex == "" && v.ExpectRequestHex == "" {
			return fmt.Errorf("adapter %s: self_test %q asserts nothing", s.Name, v.Name)
		}
	}
	return nil
}

// Capabilities lists the logical operations a spec maps, sorted.
func (s *Spec) Capabilities() []string {
	out := make([]string, 0, len(s.Operations))
	for name := range s.Operations {
		out = append(out, strings.ToLower(name))
	}
	sort.Strings(out)
	return out
}

// Op resolves an operation mapping, case-insensitively.
func (s *Spec) Op(operation string) (OpSpec, bool) {
	if op, ok := s.Operations[operation]; ok {
		return op, true
	}
	lower := strings.ToLower(operation)
	for name, op := range s.Operations {
		if strings.ToLower(name) == lower {
			return op, true
		}
	}
	return OpSpec{}, false
}

// Clone deep-copies a spec so a loaded adapter cannot be mutated underneath.
func (s *Spec) Clone() *Spec {
	raw, err := json.Marshal(s)
	if err != nil {
		return s
	}
	var out Spec
	if err := json.Unmarshal(raw, &out); err != nil {
		return s
	}
	return &out
}

// RunSelfTest exercises golden vectors against a codec.
//
// This is the gate every adapter passes before it can serve traffic, built-in
// or hot-loaded. Encoding vectors prove the adapter frames requests exactly as
// the backend expects; decoding vectors prove it parses recorded real responses
// into the right normalized shape; negative vectors prove it *rejects* the
// malformed traffic it is supposed to reject. An adapter that cannot reproduce
// bytes it never generated is not merely untested -- it is wrong, and the
// manager refuses to install it.
func RunSelfTest(spec *Spec, codec Codec) error {
	for _, v := range spec.SelfTest {
		call := Call{
			ClientRequestID: "self-test:" + v.Name,
			Operation:       v.Operation,
			Arguments:       v.Arguments,
			CorrelationID:   v.CorrelationID,
			Seq:             v.Seq,
		}

		if v.ExpectRequestHex != "" {
			want, _ := hex.DecodeString(v.ExpectRequestHex)
			got, encErr := codec.EncodeRequest(call)
			if encErr != nil {
				return fmt.Errorf("self-test %q: encode failed: %s", v.Name, encErr.Message)
			}
			if hex.EncodeToString(got) != hex.EncodeToString(want) {
				return fmt.Errorf("self-test %q: encoded request mismatch\n  want %s\n  got  %s",
					v.Name, v.ExpectRequestHex, hex.EncodeToString(got))
			}
		}

		if v.ResponseHex == "" {
			continue
		}
		raw, _ := hex.DecodeString(v.ResponseHex)
		reply, decErr := codec.DecodeResponse(raw, call)

		if v.ExpectErrorCode != "" {
			if decErr == nil {
				return fmt.Errorf("self-test %q: expected error %s, decode succeeded", v.Name, v.ExpectErrorCode)
			}
			if decErr.Code != v.ExpectErrorCode {
				return fmt.Errorf("self-test %q: expected error %s, got %s (%s)",
					v.Name, v.ExpectErrorCode, decErr.Code, decErr.Message)
			}
			continue
		}
		if decErr != nil {
			return fmt.Errorf("self-test %q: decode failed: %s: %s", v.Name, decErr.Code, decErr.Message)
		}
		if v.ExpectResult != nil {
			gotJSON, _ := json.Marshal(canonical(reply.Result))
			wantJSON, _ := json.Marshal(canonical(v.ExpectResult))
			if string(gotJSON) != string(wantJSON) {
				return fmt.Errorf("self-test %q: normalized result mismatch\n  want %s\n  got  %s",
					v.Name, wantJSON, gotJSON)
			}
		}
	}
	return nil
}

// canonical round-trips a value through JSON so that comparisons are made on
// wire-equivalent shapes rather than Go types (int vs float64, and so on).
func canonical(v any) any {
	raw, err := json.Marshal(v)
	if err != nil {
		return v
	}
	var out any
	if err := json.Unmarshal(raw, &out); err != nil {
		return v
	}
	return out
}

func parseMagic(s string) ([2]byte, error) {
	var out [2]byte
	b, err := hex.DecodeString(strings.TrimPrefix(strings.ToLower(s), "0x"))
	if err != nil {
		return out, fmt.Errorf("magic_hex %q is not valid hex: %w", s, err)
	}
	if len(b) != 2 {
		return out, fmt.Errorf("magic_hex %q must be exactly two bytes", s)
	}
	out[0], out[1] = b[0], b[1]
	return out, nil
}
